### ISSUE TITLE
Can I tidy up BODs Dev pillar?

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/opendataservices-deploy#67]
https://github.com/OpenDataServices/opendataservices-deploy/blob/master/pillar/bods_dev_pillar.sls

has 

````
# This is empty as we don't use extra_cove_branches on this server.
# Instead just change the default_branch above (that means there can only be one, but that's fine for now)
extra_cove_branches:
  - name: 16-oneof-validation
    app: cove_project
    uwsgi_port: 3033
````

Can I set this back to the empty list as it was before?

Asking @Bjwebb - thanks
