### ISSUE TITLE
Travis OCDS tests failing

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/opendataservices-deploy#98]
These fail.

I checked latest code is deployed.

First thing that must be fixed:

OCDS live is on different version of Python. Need to upgrade Travis to use that or a requirement can't be installed. Like:
```

language: python
addons:
  chrome: stable
jobs:
  include:
    - stage: test-iati-360
      python: "3.5"
      dist: xenial
      install:
        - .....
      script:
        - .......
    - stage: test-ocds
      python: "3.6"
      dist: bionic

      install:
        - ......
      script:
        - ......
```

Still fails tho. It just seems to massively start erroring half way thru.

https://travis-ci.org/github/OpenDataServices/opendataservices-deploy/jobs/663904034

No good reason I can see.

Next try: Try running locally, if errors look for better debug logs
